config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :specialities
  resources :companies

  resources :addresses do
    resources :patients, only: [:new, :create]
  end
  
  resources :patients
  
  get "up" => "rails/health#show", as: :rails_health_check


  root "patients#index"
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  has_many :doctor_specialities, dependent: :destroy
  has_many :users, through: :doctor_specialities

  validates :name, presence: true, uniqueness: true
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
  before_action :set_speciality, only: %i[ show edit update destroy ]

  # GET /specialities or /specialities.json
  def index
    @specialities = Speciality.all
  end

  # GET /specialities/1 or /specialities/1.json
  def show
  end

  # GET /specialities/new
  def new
    @speciality = Speciality.new
  end

  # GET /specialities/1/edit
  def edit
  end

  # POST /specialities or /specialities.json
  def create
    @speciality = Speciality.new(speciality_params)

    respond_to do |format|
      if @speciality.save
        format.html { redirect_to @speciality, notice: "Speciality was successfully created." }
        format.json { render :show, status: :created, location: @speciality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialities/1 or /specialities/1.json
  def update
    respond_to do |format|
      if @speciality.update(speciality_params)
        format.html { redirect_to @speciality, notice: "Speciality was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @speciality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialities/1 or /specialities/1.json
  def destroy
    @speciality.destroy!

    respond_to do |format|
      format.html { redirect_to specialities_path, notice: "Speciality was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speciality
      @speciality = Speciality.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def speciality_params
      params.expect(speciality: [ :name, :description ])
    end
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/specialities/_form.html.erb
<%= form_with(model: speciality, class: "contents") do |form| %>
  <% if speciality.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(speciality.errors.count, "error") %> prohibited this speciality from being saved:</h2>

      <ul class="list-disc ml-6">
        <% speciality.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, "Nome" %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": speciality.errors[:name].none?, "border-red-400 focus:outline-red-600": speciality.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description, "Descrição" %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": speciality.errors[:description].none?, "border-red-400 focus:outline-red-600": speciality.errors[:description].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit "Salvar Especialidade", class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/specialities/_speciality.html.erb
<div id="<%= dom_id speciality %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Nome:</strong>
    <%= speciality.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Descrição:</strong>
    <%= speciality.description %>
  </div>
</div>

app/views/specialities/edit.html.erb
<% content_for :title, "Editando a Especialidade" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editando a Especialidade</h1>

  <%= render "form", speciality: @speciality %>

  <%= link_to "Mostrar Especialidade", @speciality, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Retornar a Especialidades", specialities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/specialities/index.html.erb
<% content_for :title, "Specialities" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Especialidades</h1>
    <%= link_to "Nova especialidade", new_speciality_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="specialities" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @specialities.any? %>
      <% @specialities.each do |speciality| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render speciality %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Mostrar", speciality, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Editar", edit_speciality_path(speciality), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Deletar", speciality, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">Nenhuma especialidade encontrada.</p>
    <% end %>
  </div>
</div>

app/views/specialities/new.html.erb
<% content_for :title, "Nova Especialidade" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova Especialidade</h1>

  <%= render "form", speciality: @speciality %>

  <%= link_to "Retornar às Especialidades", specialities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/specialities/show.html.erb
<% content_for :title, "Visualizar Especialidade" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Visualizar Especialidade</h1>

  <%= render @speciality %>

  <%= link_to "Editar Espacialidade", edit_speciality_path(@speciality), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Retornar a Especialidades", specialities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Deletar Especialidade", @speciality, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>