config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :specialities
  resources :companies

  resources :addresses do
    resources :patients, only: [:new, :create]
  end
  
  resources :patients
  
  get "up" => "rails/health#show", as: :rails_health_check


  root "patients#index"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :doctor_companies, dependent: :destroy
  has_many :users, through: :doctor_companies

  validates :name, presence: true
  validates :ein, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_blank: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy!

    respond_to do |format|
      format.html { redirect_to companies_path, notice: "Company was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.expect(company: [ :name, :ein, :email, :phone, :address, :website ])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Nome da Empresa:</strong>
    <%= company.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">CNPJ:</strong>
    <%= company.ein %>
  </div>
  <div>
    <strong class="block font-medium mb-1">E-mail:</strong>
    <%= company.email %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Telefone:</strong>
    <%= company.phone %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Endereço:</strong>
    <%= company.address %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Website:</strong>
    <%= company.website %>
  </div>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, class: "contents") do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul class="list-disc ml-6">
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, "Nome da Empresa" %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": company.errors[:name].none?, "border-red-400 focus:outline-red-600": company.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :ein, "CNPJ" %>
    <%= form.text_field :ein, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": company.errors[:ein].none?, "border-red-400 focus:outline-red-600": company.errors[:ein].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :email, "E-mail" %>
    <%= form.text_field :email, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": company.errors[:email].none?, "border-red-400 focus:outline-red-600": company.errors[:email].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :phone, "Telefone" %>
    <%= form.text_field :phone, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": company.errors[:phone].none?, "border-red-400 focus:outline-red-600": company.errors[:phone].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :address, "Endereço" %>
    <%= form.text_field :address, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": company.errors[:address].none?, "border-red-400 focus:outline-red-600": company.errors[:address].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :website, "Site da Empresa" %>
    <%= form.text_field :website, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": company.errors[:website].none?, "border-red-400 focus:outline-red-600": company.errors[:website].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit "Salvar Empresa", class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% content_for :title, "Editando a Empresa" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editando a Empresa</h1>

  <%= render "form", company: @company %>

  <%= link_to "Visualizar esta Empresa", @company, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Voltar às Empresas", companies_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/companies/index.html.erb
<% content_for :title, "Empresas" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Empresas</h1>
    <%= link_to "Nova Empresa", new_company_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="companies" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @companies.any? %>
      <% @companies.each do |company| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render company %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Mostrar", company, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Editar", edit_company_path(company), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Deletar", company, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">Nenhuma empresa encontrada.</p>
    <% end %>
  </div>
</div>

app/views/companies/new.html.erb
<% content_for :title, "New company" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova Empresa</h1>

  <%= render "form", company: @company %>

  <%= link_to "Voltar para empresas", companies_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/companies/show.html.erb
<% content_for :title, "Showing company" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Empresa</h1>

  <%= render @company %>

  <%= link_to "Editar empresa", edit_company_path(@company), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Retornar as Empresas", companies_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Deletar Empresa", @company, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>